### PR TITLE
Added initial score of 0

### PR DESCRIPTION
**Pull request by joosthoi1**
Upon first cloning the game wouldn't open because this file isnt present, if you want you could also make it automatically create the file if it's not found.

### CODE REVIEW

**Comment by mozartilize** [comment]
Hi, I'm quite happy because of your interest in my learning purpose small game.

I'm aware about the issue and my plan is update func `max_score` to handle exception if the file not exist. Because in the future I want to build binary for it (using pyinstaller for example) or upload it on pypi so the score file will be placed somewhere in user's home directory.

**Comment by joosthoi1** [comment]
okay, if you want I can add this for you?

**Comment by joosthoi1** [comment]
also, maybe gitignore your test things

**Comment by mozartilize** [comment]
The func has been fixed and the game released. Thanks

**Pull request closed without merging**
